CREATE TABLE tenant (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    room_no VARCHAR(20) NOT NULL,
    phone_no VARCHAR(15) NOT NULL,
    email VARCHAR(100),
    meter_id VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
